diversityFIRST/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home_page')),
] 
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


app_name ="home"

from home.views import (
	TemplatePage,
	HomePage,
	GeneratePdf,
	AmbassadorPage,
	)

urlpatterns = [
	path('template-creator/', 
		TemplatePage.as_view(), 
		name="template-creator"),
	path('', HomePage.as_view(), name="home_page"),
	path('pdf', GeneratePdf.as_view(), name="pdf"),
	# path('ea9f91b2cda019730f2891bd12a7a4d6/', ExtraView.as_view(), name="extra"),
	path('ambassador-program/', AmbassadorPage.as_view(), 
		name="ambassador-program"),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models


# Create your models here.
class AmbassadorData(models.Model):
	team_name = models.CharField(max_length=50, blank=False
#		required=False
	)
	team_email = models.EmailField(max_length=200, blank=False)

	message = models.CharField(max_length=1000, blank=True)


	def __str__(self):
		return '%s'% (self.team_name)

class TemplateData(models.Model):



	message = models.CharField(
		max_length=500,
#		min_length=5,
#		required=False
)

	team_name = models.CharField(max_length=50, 
#		required=False
		)
	size = models.CharField(max_length=3, 
#		required=False
		)

	def __str__(self):
		return self.team_name

class TeamPhoto(models.Model):
	team_name = models.CharField(max_length=50, 
#		required=False
		)
	Image = models.ImageField()


	def __str__(self):
		return '%s'% (self.team_name)

home/forms.py
from django import forms
from home.models import TemplateData, AmbassadorData

class AmbassadorForm(forms.ModelForm):

	class Meta:
		model = AmbassadorData
		fields = ('team_name', 'team_email', 'message')

	def __init__(self, *args, **kwargs):
		super(AmbassadorForm, self).__init__(*args, **kwargs)

		t_name = self.fields['team_name']
		t_name.required = True

		t_email = self.fields['team_email']
		t_email.required = True

		message = self.fields['message']
		message.required = False
		message.label = 'How are you going to use this ambassadorship?'


class TemplateForm(forms.ModelForm):

	class Meta:
		Size_choices = (
			('A4', 'A4'),
			('A3', 'A3'),
			)
		model = TemplateData
		fields = ('message','team_name', 'size') 

		widgets = {
		'message': forms.TextInput(attrs={'id': "message_field"}),
		'size': forms.Select(choices=Size_choices),
		}
		labels = {
		'message': 'Your Message:',
		'team_name': 'Team Name:',
		'size': 'Poster Size:'
		}

		help_text = {
		'message': 'How you do #DiversityFIRST within your team.', 
		'team_name': 'Your team name.',
		}

	def __init__(self, *args, **kwargs):
		super(TemplateForm, self).__init__(*args, **kwargs)
		msg = self.fields['message']
		msg.min_length = 5
		msg.required = False


		t_m = self.fields['team_name']
		t_m.required = True

		sz = self.fields['size']
		sz.required = False

home/views.py
import requests


from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import View
from home.template_generator import Badge_Reporter
from django.template.loader import get_template

from django.conf import settings # import the settings file


from django.utils.decorators import method_decorator
from home.forms import TemplateForm, AmbassadorForm
from home.utils import render_to_pdf #created in step 4
from home.models import TeamPhoto

from easy_pdf.views import PDFTemplateView



class TemplatePage(TemplateView):
	template_name = 'home/template-creator.html'

	def get(self, request):
		template_form = TemplateForm()
		
		
		args = {'form': template_form}
		return render(request, self.template_name, args)
	def post(self, request):
		form = TemplateForm()		
		args = {'form': form}

		form_info = TemplateForm(request.POST)
		if form_info.is_valid():
			info = form_info.save()

			print('post accepted 2.')
			msg = form_info.cleaned_data['message']
			team_name = form_info.cleaned_data['team_name']
			size = form_info.cleaned_data['size']
			print (msg)
			#print the message out too
			context = {
				"message": msg,
				"team_name": team_name,
				}

			pdf = render_to_pdf(request, 'pdf/poster.html', context, size=size)
			if pdf:
				
				response =  HttpResponse(pdf, content_type='application/pdf')
				filename = "diversityFIRST"
				content = "inline; filename='%s'" %(filename)
				download = request.GET.get("download")
				if download:
					content = "attachment; filename='%s'" %(filename)
				response['Content-Disposition'] = content
				return response
			return HttpResponse("Not Found")

		else:
			print(False)
			return render(request, self.template_name, args)

class HomePage(TemplateView):
	template_name = 'home/home_page.html'


	def get(self, request):
		template_form = TemplateForm()
		#collecting all the photios and putting them in a list
		ph_list = []
		ph_data = TeamPhoto.objects.all()
		for photo in ph_data:
			ph_list.append(photo)
		#list 

		args = {'form': template_form, 'photo_data': ph_list}
		return render(request, self.template_name, args)

	def post(self, request):
		form = TemplateForm()		
		args = {'form': form}

		form_info = TemplateForm(request.POST)
		if form_info.is_valid():
			team_name = form_info.cleaned_data['team_name']
			print (team_name)
			info = form_info.save(commit=False)

			if team_name == '' or team_name == None:
				team_name == 'N/A'
			info.team_name = team_name
			info.save()

			msg = form_info.cleaned_data['message']
			print('post accepted.')
			size= form_info.cleaned_data['size']
			#print the message out too
			context = {
				"message": msg,
				"team_name": team_name,
				}

			pdf = render_to_pdf(request, 'pdf/poster.html', context, size=size)
			if pdf:
				
				response =  HttpResponse(pdf, content_type='application/pdf')
				filename = "diversityFIRST"
				content = "inline; filename='%s'" %(filename)
				download = request.GET.get("download")
				if download:
					content = "attachment; filename='%s'" %(filename)
				response['Content-Disposition'] = content
				return response
			return HttpResponse("Not Found")

		else:
			print(False)
			return render(request, self.template_name, args)

class PosterView(PDFTemplateView):
	template_name = 'hello.html'

class GeneratePdf(View):
	def get(self, request, *args, **kwargs):
		context = {
				"invoice_id": 123,
				"customer_name": "Felix Hall",
				"amount": 1399.99,
				"date": "Today",
			}

		pdf = render_to_pdf('pdf/invoice.html', context)
		if pdf:
			response =  HttpResponse(pdf, content_type='application/pdf')
			filename = "filename"
			content = "inline; filename='%s'" %(filename)
			download = request.GET.get("download")
			if download:
				content = "attachment; filename='%s'" %(filename)
			response['Content-Disposition'] = content
			return response
		return HttpResponse("Not Found")


class AmbassadorPage(TemplateView):
	template_name = "home/ambassador-program.html"

	def get(self, request):
		form = AmbassadorForm()
		args = {'form': form}
		return render(request, self.template_name, args)


	def post(self, request):
		form = AmbassadorForm()
		args = {'form': form}

		form_info = AmbassadorForm(request.POST)

		if form_info.is_valid():
			print('AmbassadorForm form accepted')
			team_name = form_info.cleaned_data['team_name']
			team_email = form_info.cleaned_data['team_email']
			message = form_info.cleaned_data['message']
			info = form_info.save(commit=False)

			if message == '' or message == None:
				message = 'Undecided'
			info.message = message
			info.save()

			print('AmbassadorForm saved')
			args['form_saved'] = True
			query_data= {
			'team_name': team_name,
			'team_email': team_email,
			'message': message,
			}
			post_url = settings.ZAPIER_EMAIL_WEBHOOK_URL

			r = requests.post(post_url, data=query_data)

		return render(request, self.template_name, args)

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_TAG }}"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-153167626-1');
  </script>



		<!-- Bootstrap stuff -->
    {% load staticfiles %}
    {% load static %}

{# JQuery? #}
<script src="https://code.jquery.com/jquery-3.1.1.js"></script>
<!--
<script src="{% static 's/jquery-1.11.1.js' %}"></script>
<script src="{% static 'js/rango-jquery.js' %}"></script>
-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

{# angluar #}
<!--
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
-->
{# AOS #}
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">


{# Pace, loading #}
<!--
script src="{% static 'pace/pace.js' %}">/script>
link href="{% static 'pace/themes/white/pace-theme-flash.css' %}" rel="stylesheet" />
-->

{# bootstrap #}
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<!-- Responsive meta tag -->
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

{# font awesome #}
<script src="https://use.fontawesome.com/0f9fd014d4.js"></script>


    {% block extra_styles %}
    <style type="text/css">

      body{
        color: black;
        background: #343a40;
 

      }

    </style>
    {% endblock %}
		{% block head %}
		<title>Base</title>
		{% endblock %}
	</head>
	{% block body-tag %}<body>{% endblock %}

{% block navbar %}


<nav
id="navBar" 
style="display: none;"
class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
<a class="navbar-brand mr-auto mr-lg-0" href="{% url 'home:home_page' %}"><strong>#DiversityFIRST</strong></a>

<!--
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <div class="navbar-nav">
<a class="nav-item nav-link" href="#">Template Creator<span class="sr-only"></span></a>

     Extra labels
    <a class="nav-item nav-link" href="#">Home</a>
     <a class="nav-item nav-link" href="#">About Us</a>

</div>
</div>
-->
</nav>


</body>
{% endblock %}
<br><br>
			{% block body %}
			{% endblock %}
<!-- {% block footer %}
<footer class="footer" style="background-color: ghostwhite">
      <div class="container-fluid">
        <span class="text-muted">A website for the ease of scouting.</span>
      </div>
    </footer>
    {% endblock %} -->

<script>
  AOS.init();
</script>



				<!-- jQuery first, then Tether, then Bootstrap JS. -->
				<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
				<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
				<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
	</body>
</html>

home/templates/base64/googlefont_stylesheet.html
<link href='data:text/css;base64,aHR0cDovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2Nzcz9mYW1pbHk9TWVyaWVuZGErT25l' rel='stylesheet' type='text/css'>

home/templates/bf_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
	{{ hidden_field}}
{% endfor %}

{# non field errors #}
{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
			{{  error.as_p }}
		{% endfor %}
	</div>
{% endif %}

{# actual form #}
{% for field in form.visible_fields %}
<div class="form-group">
	{{ field.label_tag }}

	{# bound = has data #} 
	{% if form.is_bound %}	}
		{% if field.errors %}
		{% render_field field class="form-control is-invalid" %}
		{% for error in field.errors %}
		<div class="invalid-feedback">
			{{ error.as_p }}
		</div>
		{% endfor %}
	{% else %}
		{# else = form is valid -- show a green box #}
		{% render_field field class="form-control is-valid" %}
	{% endif %}
	{% else %}
		{# else to if field is bound #}
		{% render_field field class="form-control" %}
	{% endif %}

{% if field.help_text %}
	<small class="form-text text-muted">
		{{ field.help_text.as_p }}
	</small>
	{% endif %}
</div>
{% endfor %}

home/templates/home/ambassador-program.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

<title>DiversityFIRST - Home</title>
<style type="text/css">



#header_block{

	background-color: #343a40;
	text-align: center; 
}
#header_img{
	display: block;
	margin-left: auto;
	margin-right: auto;
	margin-top: 4vh;
	height: auto;
	width: 50vw;



}

.hbr{
	display: block;
	font-size: 50vh;
}

#Welcome_Mission{
	text-align: center;
	background: orange;
}

#mission_txt{
	text-align: center;
	margin-right: 8vw;
	margin-left: 8vw;
}

#carousel-container{
	text-align: center;
	background-color: #343a40;
}

.center-list-center{
	display: inline-block;
    text-align:center;
    align-self: center;
   margin-left:auto;
   margin-right:auto;
/*   display:block;
*/}

.center-list-left{
	display: inline-block;
    text-align:left;
    align-self: center;
   margin-left:auto;
   margin-right:auto;
/*   display:block;
*/}
}
</style>

{% endblock %}

{% block body %}

<div data-aos="fade" data-aos-duration="3000">
	<img id="header_img" src="{% static 'img/dark_logo2.png' %}">
	<div id="header_block">
		<h1><font color="white"><strong>Be part of the movement</strong></font></h1>
		<br>
	</div>
</div>

<div class="container-fluid" id="Welcome_Mission">
	<br>
	<h2><strong>We are excited to have you part of this journey!</strong></h2>
	<h3 id="mission_txt">Part of celebrating diversity is getting everyone on board. We know you want to work on your robot and sometimes doing impactful outreach can be hard... so we've made a program which makes the most of your time.</h3>
	<br>
<!-- 	<div class="row" style="text-align: left;">
	<div class="col-5">
 -->		
	 <h4>Why join? Well it can give strong outreach benefits by:</h4>
		<div class="row">
			<div class="col-6">
				<div class="center-list-center">
					<p>
					<i class="fa fa-heart" aria-hidden="true"></i>
Giving something you can talk about for <strong>outreach</strong></li>
						
					</p>
					<p>
					<i class="fa fa-heart" aria-hidden="true"></i>
<strong>Giving you a voice</strong> with promoting diversity within FIRST</li>
					</p>
				</div>
				
			</div>
			<div class="col-6">
				<div class="center-list-center">
					<p>
					<i class="fa fa-heart" aria-hidden="true"></i>
Getting you a cool logo on that T-Shirt of yours :)</li>
						
					</p>
					<p>
					<i class="fa fa-heart" aria-hidden="true"></i>
Giving you <strong>outreach bragging rights</strong> because you're actually doing something cool
					</p>
						
				</div>
					</div>
				
			
		</div>
		<br>
 		
	<!-- </div>
	<div class="col-5"> -->
		<h4>Is it much work? Nope, all you would have to:</h4>
		<ol class="center-list-left">
			<li>Print and laminate an A3 #diversityFIRST poster</li>
			<li>Find teams during your match day or similar</li>
			<li>Get them to write how they do diversity on a #diversityFIRST poster</li>
			<li>Take a photo with the team and repeat</li>
			<li>Upload photos here or share on instagram with the tag: #diversityFIRST</li>
		</ol>
<!-- 	</div>
		
	</div>
 -->	<br>



<form role="form" method="post">
	{% csrf_token %}
	{% include 'bf_form.html' with form=form %}

	<br>
	<button type='submit' class="btn btn-dark" style="width:100%"><i class="fa fa-paper-plane-o"></i> Begin!</button>

</form>
<br>
<br>
<h3 style="text-align: left">
	
<a style="color: grey" href="{% url 'home:home_page' %}"><i class="fa fa-chevron-circle-left"></i>
 Take me back to the homepage</a>
</h3>
</div>
<br>

<br>



{% endblock %}

home/templates/home/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

<title>DiversityFIRST - Home</title>
<style type="text/css">



#header_block{

	background-color: #343a40;
	text-align: center; 
}
#header_img{
	display: block;
	margin-left: auto;
	margin-right: auto;
	margin-top: 4vh;
	height: auto;
	width: 50vw;



}

.hbr{
	display: block;
	font-size: 50vh;
}

#Welcome_Mission{
	text-align: center;
	background: orange;
}

#mission_txt{
	text-align: center;
	margin-right: 8vw;
	margin-left: 8vw;
}

#carousel-container{
	text-align: center;
	background-color: #343a40;
}

</style>
{% endblock %}

{% block body %}
<div data-aos="fade" data-aos-duration="3000">
	<img id="header_img" src="{% static 'img/dark_logo2.png' %}">
	<div id="header_block">
		<h1><font color="white"><strong>Be part of the movement</strong></font></h1>
		<br>
	</div>
</div>

	{# The Mission #}
<div class="container-fluid" id="Welcome_Mission">
	<br>
	<h2><strong>The Mission:</strong></h2>
	<h3 id="mission_txt">#DiversityFIRST is an @ftcbeast12990 initiative, launched in 2018, to showcase the diversity of FIRST participants in teams across the world!</h3>
	<br>
	<br>
	{# template creator #}
	<h2><strong>Get Involved!</strong></h2>
	<h3 id="marker"></h3>

	{% include 'home/template-creator.html' with form=form %}

	<h2>If you want to do more, why not <a href="{% url 'home:ambassador-program' %}">become an ambassador</a>?</h2>

</div>
	
	{# photo display #}

<div class="container-fluid" id="carousel-container" style="background-color: #343a40;">
	<h2 style="color: white;">Thank you!</h2>
	<br>

	{# carousel #}


	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	  <ol class="carousel-indicators">
	  	{% for photo in photo_data %}
			{% if 'team_image' not in photo.Image.url %}

				{% if forloop.first %}
			    <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
				{% else %}
			    <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}"></li>
			    {% endif %}
		    {% endif %}
	    {% endfor %}
	  </ol>
	    
		{% for photo in photo_data %}
			{% if 'team_image' not in photo.Image.url %}

				{% if forloop.first %}
				<div class="carousel-item active">
					<img class="team_photo" src="{{ photo.Image.url }}" alt="{{ photo.team_name }}">
					<div class="carousel-caption d-none d-md-block">
						<h4 style="color: white;">{{ photo.team_name }}</h4>
					</div>
				</div>
				{% else %}
				<div class="carousel-item">
				<img class="team_photo" src="{{ photo.Image.url }}" alt="{{ photo.team_name }}">
					<div class="carousel-caption d-none d-md-block">
						<h4 style="color: white;">{{ photo.team_name }}</h4>
					</div>
				</div>
				{% endif %}

				{% endif %}
				{% endfor %}
	<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
	<span class="carousel-control-prev-icon" aria-hidden="true"></span>
	<span class="sr-only">Previous</span>
	</a>
	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
	<span class="carousel-control-next-icon" aria-hidden="true"></span>
	<span class="sr-only">Next</span>
	</a>
	</div>
</div>
<br>
</div>
<br>






{% endblock %}

home/templates/home/poster.html
{% extends "easy_pdf/base.html" %}

{% block content %}
    <div id="content">
        <h1>Hi there!</h1>
    </div>
{% endblock %}

home/templates/home/template-creator.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>DiversityFIRST - template creator</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/old_preview2.css' %}">
<script src="{% static 'js/pg_sizing4.js' %}"></script>
<script src="{% static 'js/home_page.js' %}"></script>
<link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">



<style type="text/css">
@font-face{
	font-family: 'Lucida Calligraphy';
	src: 
		"{% static 'fonts/22799_LCALLIG.woff' %}" format('woff'),
		"{% static 'fonts/22799_LCALLIG.ttf' %}" format('ttf');
}

@media screen and (min-width: 700px){

    .box{
	    position: relative;
	    width: 30vw ! important;
	    max-width: 500px ! important;
	    max-height: calc(500px*0.7071) ! important;
	    height: 25vw ! important;


    }
	.GridBox {
		box-sizing: border-box;
		margin: 0;
		padding: 0;
		border: 0;
		grid-gap: 15px 10px;


		width: 100%;
		max-width: 100vw;

		display: grid ! important;
		grid-template-columns: 60% 40%;
		grid-template-rows: auto;
		grid-template-areas: 
			"form" "preview";
	  
	}

	.col1, .col2 {
		width: 100%;
		height: 100%;
		display: grid ! important;
		grid-row: 1 / span 1;


	}

	.col1{

		grid-area: form;
		grid-column: 1 / span 1;
	}

	.col2{
		grid-column: 2 / span 1;

	}

	.preview{
		max-width: 500px ! important;
	    max-height: calc(500px*0.7071) ! important;

	}
}
@media screen and (max-width: 1300) and (min-width: 700){
	.box{
	    width: 100%;
	    max-width: 500px ! important;
	    max-height: calc(500px*0.7071) ! important;
	    height: 100%;
    }
    .pretitle {
		font-size: 150% ! important;
	}
}
@media screen and (max-width: 700){
		.box{
		    width: 60vw ! important;
		    max-width: 500px ! important;
		    max-height: calc(500px*0.7071) ! important;
		    height: 42.5vw ! important;
    }
}
@media screen and (min-width: 1300){
	.box{
	    width: 45vw;
	    max-width: 500px ! important;
	    max-height: calc(500px*0.7071) ! important;
	    height: 31.75vw;
	    }
    .pretitle{
    	font-size: 200% ! important;
    }

}
.pretitle {
	font-family: 'Verdana','Times New Roman', sans-serif;
	font-size: 150%;
	padding-top: 6% ! important;
	padding-left: 0.75vw;
	font-weight: 900 !important;
	font-style: italic;

	text-align: left;
             }


    .predetails {
    padding-left: 0.75vw;
    padding-right: 18vw;
    padding-top: 3.2vh; 
    font-size: 4.5vh !important;
    font-weight: 550;
    position: absolute;
    word-break: keep-all;

    font-family: 'Tangerine', 'Lucida Calligraphy','Freestyle Script';
    text-shadow: 3px 3px 3px #fff;
    text-align: left !important;
    /*margin-left: 40%;*/
    }

    .Diversity
    {
    color: orange;
    }

</style>
{% endblock %}

{% block body %}
<h4>Fill in the form below to tell your team's story about putting #DiversityFIRST.</h4>
<h6 style="opacity: 0.5;"><i>Please note, you can get a blank poster by leaving the team and message fields blank.</i></h6>
<br>
<div id ="GridBox" class="GridBox container">
	<div class="col1">
		<form role="form" method="post">
		{% csrf_token %}
		{% include 'bf_form.html' with form=form %}
		<button id="sm_down" type='submit' class="btn btn-dark" style="width:100%; display: none;"><i class="fa fa-download"></i> Download</button>
		</div>

	    <div class="col2">

			<div id="box_js2" class="box" 
			style="
			display: block; text-align: left;"
			>
				<div id="box_js" class='preview'>
				<p></p>
				<strong><h1 class='pretitle'>We put <font color="orange">#DiversityFIRST</font> by...</h1></strong>
				<br>
				<h2 class='predetails' id='message'></h2> 
					<div style="
					position: absolute;
					bottom: 0% ! important;
					text-align: right;
					right: 0 ! important;
					padding-right: 0 !important;
					height: auto;
					width: 100%;

					">
					{% include 'base64/#diversity_logo.html' with widthS=25 %}
				</div>
			</div>
		</div>
	</div>

<br>
	<button id="lg_down" type='submit' class="btn btn-dark" style="width:100%"><i class="fa fa-download"></i> Download</button>

	</form>
	<br>
	<br>
</div>
    <br><br>
    <br>
 <script type="text/javascript">


var row_c = document.getElementById("GridBox");
var sm_down = document.getElementById("sm_down");
var lg_down = document.getElementById("lg_down");


if (row_c.offsetWidth >= 720){
	lg_down.style.display = 'none';
	sm_down.style.display = 'block';
} else {
	lg_down.style.display = 'block';
	sm_down.style.display = 'none';
}

/* Make preview set smaller once broken*/
var prebox1 = document.getElementById("box_js");
var width1 = prebox.offsetWidth;

var prebox2 = document.getElementById("box_js2");
var width2 = prebox2.offsetWidth;
prebox2.style.padding-top = width2 * 0.7071

/*if (prebox.getComputedStyle.width >= "500px"){ */
if ((width1 >= 500) || (width2 >= 500)){
	prebox1.style.height = (500*0.7071);
	alert("done");
	prebox2.style.height = (500*0.7071);
}


 </script>


{% endblock %}

home/templates/pdf/poster.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>
         <title>#Diversity FIRST Poster</title>
<link href="//fonts.googleapis.com/css?family=Merienda" rel="stylesheet">


     </head>
     <body>
            <div class='container'>
                 <strong><h1 class='title'>We put <font color="orange">#DiversityFIRST</font>  by...</h1></strong>
             <h2 class='details'>{{ message }}</h2> 
             </div>
     </div>
         <div id="footer">
            <div style="float: right !important;">
                {% include 'base64/#diversity_logo.html' %}
        </div>

     </body>
 </html>